@TransProAPI_HostAddress = http://localhost:5070

GET {{TransProAPI_HostAddress}}/api/Customers
Accept: application/json

###

POST {{TransProAPI_HostAddress}}/api/Customers
Content-Type: application/json
Accept: application/json

{
  "fullName": "Maxim Overseas",
  "email": "sales+1@maxim.com",
  "phone": "9896989698",
  "address": "Ahmedabad"
}

###
PUT {{TransProAPI_HostAddress}}/api/Customers/3
Content-Type: application/json
Accept: : application/json

{
  "fullName": "RM Foods Pvt Ltd",
  "phone": "8887774500",
  "address": "Mahuva, Rajkot"
}

###
DELETE {{TransProAPI_HostAddress}}/api/Customers/2
Accept: : application/json

###